site_name: OOIP for Controls and Automation Engineers
site_description: Object-Oriented Industrial Programming patterns and features for CODESYS
site_author: Jacob Lawson

site_url: https://jake1510.github.io/ooip-tutorial-library/
use_directory_urls: true
docs_dir: docs

extra_css:
  - private/styles/extra.css

theme:
  name: material
  logo: private/assets/profile-image.png
  favicon: private/assets/profile-image.png
  palette:
    - scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

    - scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Features:
      - Function Blocks: features/FunctionBlocks.md
      - Methods: features/Methods.md
      - Properties: features/Properties.md
      - Interfaces: features/Interfaces.md
  - Patterns:
      - State Machine: patterns/StateMachine.md
      - Dependency Injection: patterns/DependencyInjection.md
      - Command: patterns/Command.md
  - Examples Folder: https://github.com/Jake1510/codesys-ooip-library/tree/main/examples

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
