site_name: OOIP for Controls and Automation Engineers
site_description: Object-Oriented Industrial Programming patterns and features for CODESYS
site_author: Jacob Lawson

extra_css:
  - private/styles/extra.css

theme:
  name: material
  logo: private/assets/profile-image.png
  favicon: private/assets/profile-image.png   
  palette:
    primary: indigo
    accent: light blue
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Features:
      - FunctionBlocks: features/FunctionBlocks.md
  - Patterns:
      - Singleton: Patterns/Singleton.md
      - Command: Patterns/Command.md
  - Examples Folder: https://github.com/Jake1510/codesys-ooip-library/tree/main/examples

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
